# Generated by Django 5.0.7 on 2024-07-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
