# Generated by Django 5.0.7 on 2024-07-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0002_trip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='TripPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_position', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=5, null=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_planner.poi')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_planner.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='pois',
            field=models.ManyToManyField(through='trip_planner.TripPOI', to='trip_planner.poi'),
        ),
    ]
