# Generated by Django 5.0.7 on 2024-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0003_poi_trip_details_alter_trip_description_trippoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
