# Generated by Django 5.0.7 on 2024-07-17 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0004_alter_poi_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='poi',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_planner.location'),
        ),
    ]
