# Generated by Django 5.0.7 on 2024-07-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0005_location_poi_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='lon',
        ),
    ]
