# Generated by Django 5.0.7 on 2024-07-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0007_alter_location_lat_alter_location_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trippoi',
            old_name='poi_position',
            new_name='position',
        ),
    ]
