# Generated by Django 5.0.7 on 2024-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0008_rename_poi_position_trippoi_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='trippoi',
            name='position',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=5, null=True),
        ),
    ]
