# Generated by Django 5.0.7 on 2024-07-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0009_remove_trip_end_date_remove_trip_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(),
        ),
    ]
