# Generated by Django 5.0.7 on 2024-07-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0010_alter_location_lat_alter_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_planner.location'),
        ),
    ]
